baseURL = 'https://UsagiKnight.github.io/PapermodBlog/'
languageCode = 'zh-cn'
title = 'Usagi'
theme = 'PaperMod'
copyright = "© 2025 UsagiKnight. All rights reserved"

[params]
  custom_css = ["css/custom.css"]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "叼烟斗的乌萨奇"
    Content = "此去必经年，荒野寒暑换红颜。 往事散云烟，十寸光阴换一钱。"

  [[params.socialIcons]]
      name = "github"
      url = "https://github.com/UsagiKnight/"
  [[params.socialIcons]]
      name = "email"
      url = "mailto:quanningzhen@gmail.com"
  [[params.socialIcons]]
      name = "x"
      url = "https://x.com/UsagiiKnight"

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1_000
    threshold = 0.4
    minMatchCharLength = 0
    keys = [ "title", "permalink", "summary", "content" ]

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "分类"
    url = "/tags/"
    weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[taxonomies]
  tag = "tags"
  category = "categories"